### PR TITLE
Make python 3 compatible

### PR DESCRIPTION
**Pull request by naoko**
It would be great if we can add test with tox

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Thanks this was really needed. And yes I agree a test suite is needed. Feel free to contribute it if you are willing to!

**Comment by naoko** [comment]
Great! Thank you so much!

**Comment by bittner** [comment]
@naoko Will you add the tox configuration?

Actually, that would need tests to make sense. I don't see any. We can still add a "test infrastructure" and maybe run static code analysis over the source code. And add badges to the README. Just to start with. Much like I have done recently with the [SentryLogs](https://github.com/mdgart/sentrylogs) package.

**Comment by nicolaiarocci** [comment]
hey @bittner, nice to see you around these parts 😄 

I'm targeting v0.0.6 for a test suite, see #8

**Pull request merged**
