### PR TITLE
Add the ability to generate swagger tags

### PR DESCRIPTION
**Pull request by stratosgear**
This adds the ability to output swagger tags.

Getting the tag name is easy, I'm using the `item_title` from the resource.  But, having a nice tag description, like "Everything about your Pets" (as in http://petstore.swagger.io/) is kinda tricky.  There is no way to provide this info, apart from a `description` field that i added at the same level as the Item / Resource Endpoints (as `item_title` is)

It's only purpose so far it is to be used in the swagger documentation, as a description for the tag, and I have no idea how to add it or document it in the actual Eve documentation. 

As of now then, it behaves like an undocumented feature, for now.

### CODE REVIEW

**Comment by nicolaiarocci** [comment]
Could you update the README with a mention of the newly added resource-level `description` field? So eve-swagger adopters know about it.

**Comment by otibsa** [comment]
The resource level description field was already introduced in #17.

See https://github.com/nicolaiarocci/eve-swagger#description-fields-on-the-swagger-docs

**Comment by nicolaiarocci** [comment]
aww sorry about that.

**Comment by stratosgear** [comment]
So, I take it, we're OK with documentation now...

**Comment by nicolaiarocci** [comment]
Yup I'm merging it!

**Pull request merged**
